### ISSUE TITLE
[chapters] Interest in Ottawa, ON

### ISSUE THREAD

**Issue by prushforth** [JSFoundation/standards#51]
Chapters.IO, that is.  Don't have rights to tag / label.  Thanks!

**Comment by bkardell** [comment]
It sounds like maybe there is some interest from the Ottawa JavaScript organizer, I'll leave here for replies.  I see @AmeliaBR has tagged a number of other Ottawa meetups as well in https://twitter.com/AmeliasBrain/status/773990320472109056

**Comment by bkardell** [comment]
@ottawajs is who we were looking for I guess....

**Comment by prushforth** [comment]
Will raise an issue with them about piggybacking a pitch for an Ottawa Chapter at the next meetup. I have been to a couple of their meetups in the past.

**Comment by bkardell** [comment]
So, I think @prushforth initiated the first meeting there -- is this issue good to go, can we close it?

**Comment by prushforth** [comment]
Yes, we're all  set up, our second meeting will be mid-December.
